version: "3.4"

services:
    db:
        image: "postgres:9.6"
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_PASSWORD: b245005e8b3df99ac373f72240ba14df
        networks:
            - dbnet
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 100M
            restart_policy:
                condition: any
                window: 3m
            update_config:
                parallelism: 1
                delay: 3m
                failure_action: rollback
                monitor: 3m
                max_failure_ratio: 0.1
                order: stop-first
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"] 
            interval: 30s
            timeout: 30s
            retries: 3

    api:
        image: "seboschtion/cldinflab11_api"
        networks:
            - apinet
            - dbnet
        depends_on:
            - db
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.1"
                    memory: 100M
            restart_policy:
                condition: any
                window: 3m
            update_config:
                parallelism: 1
                delay: 3m
                failure_action: rollback
                monitor: 3m
                max_failure_ratio: 0.1
                order: stop-first

    web:
        image: "seboschtion/cldinflab11_web"
        networks:
            - webnet
            - apinet
        depends_on:
            - api
        ports:
            - "8080:80"
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.1"
                    memory: 100M
            restart_policy:
                condition: any
                window: 3m
            update_config:
                parallelism: 1
                delay: 3m
                failure_action: rollback
                monitor: 3m
                max_failure_ratio: 0.1
                order: stop-first

networks:
    dbnet:
        internal: true
    apinet:
        internal: true
    webnet:
        internal: false
